CREATE TABLE IF NOT EXISTS ROLES (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL,
	CODE INT NOT NULL
);
INSERT INTO ROLES (NAME, CODE)
VALUES ('Customer', 10000),
	('Writer', 10001),
	('Admin', 10002);

CREATE TABLE IF NOT EXISTS USERS (
	ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	USERNAME VARCHAR(50),
	EMAIL VARCHAR(300) NOT NULL,
	PASSWORD VARCHAR(300) NOT NULL,
	ROLE_ID INT NOT NULL,
	FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID),
	VERIFIED BOOL DEFAULT FALSE NOT NULL,
	IS_ACTIVE BOOL DEFAULT TRUE NOT NULL,
	CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP WITH TIME ZONE,
	DELETED INT DEFAULT 0 NOT NULL,
	DELETED_AT TIMESTAMP WITH TIME ZONE,
	UNIQUE (EMAIL, USERNAME, DELETED)
);

CREATE TABLE IF NOT EXISTS VERIFICATIONS (
	ID SERIAL PRIMARY KEY,
	USER_ID INT NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
	ACCOUNT BOOL NOT NULL,
	PASSWORD BOOL NOT NULL,
	EMAIL BOOL NOT NULL,
	DELETION BOOL NOT NULL,
	NEW_EMAIL VARCHAR(300),
	VERIFICATION_TOKEN VARCHAR(300) NOT NULL,
	EXPIRES_AT TIMESTAMP WITH TIME ZONE DEFAULT (CURRENT_TIMESTAMP + INTERVAL '30 minutes') NOT NULL,
	CONFIRMED BOOL DEFAULT FALSE NOT NULL,
	CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS SESSIONS (
	ID SERIAL PRIMARY KEY,
	USER_ID INT NOT NULL,
	SESSION_TOKEN VARCHAR(300) NOT NULL,
	EXPIRED BOOL DEFAULT false NOT NULL,
	CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP WITH TIME ZONE,
	DELETED INT DEFAULT 0 NOT NULL,
	DELETED_AT TIMESTAMP WITH TIME ZONE,
	UNIQUE (USER_ID, SESSION_TOKEN, DELETED)
);