CREATE TABLE IF NOT EXISTS BANNERS (
	ID SERIAL PRIMARY KEY,
	HEADER VARCHAR(50) NOT NULL,
	SUB_HEADER VARCHAR(50) NOT NULL,
	BACKGROUND_PATH VARCHAR(500) NOT NULL,
	BUTTON_TEXT VARCHAR(20) NOT NULL,
	BUTTON_LINK VARCHAR(500) NOT NULL,
	IS_ACTIVE BOOL DEFAULT FALSE NOT NULL,
	ACTIVE_TILL TIMESTAMP WITH TIME ZONE,
	CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP WITH TIME ZONE,
	DELETED INT DEFAULT 0 NOT NULL,
	DELETED_AT TIMESTAMP WITH TIME ZONE
);