CREATE TABLE IF NOT EXISTS BLOGS (
	ID SERIAL PRIMARY KEY,
	AUTHOR_ID INT NOT NULL,
	FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID),
	TITLE VARCHAR(150) NOT NULL,
	SLUG VARCHAR(300) NOT NULL,
	BANNER_PATH VARCHAR(1000) NOT NULL,
	DESCRIPTION VARCHAR(300) NOT NULL,
	SUB_DESCRIPTION VARCHAR(300),
	RAW_CONTENT TEXT,
	CONTENT TEXT,
	PUBLISHED BOOL DEFAULT FALSE NOT NULL,
	PUBLISH_DATE TIMESTAMP WITH TIME ZONE,
	CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP WITH TIME ZONE,
	DELETED INT DEFAULT 0 NOT NULL,
	DELETED_AT TIMESTAMP WITH TIME ZONE,
	UNIQUE (TITLE, SLUG, BANNER_PATH, DELETED)
);