CREATE TABLE IF NOT EXISTS SUBSCRIBER (
	ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(300) NOT NULL,
	TOKEN VARCHAR(150) NOT NULL,
	SUBSCRIBED BOOLEAN DEFAULT TRUE NOT NULL,
	CREATED_AT TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP with time zone,
	UNIQUE (EMAIL, TOKEN)
);