CREATE TABLE IF NOT EXISTS TEAM_MEMBERS (
	ID SERIAL PRIMARY KEY,
	FULL_NAME VARCHAR(100) NOT NULL,
	JOB_POSITION VARCHAR(50) NOT NULL,
	SHORT_DESCRIPTION VARCHAR(100) NOT NULL,
	FACEBOOK_LINK VARCHAR(500),
	TWITTER_LINK VARCHAR(500),
	YOUTUBE_LINK VARCHAR(500),
	PINTEREST_LINK VARCHAR(500),
	INSTAGRAM_LINK VARCHAR(500),
    IMAGE_PATH VARCHAR(500) NOT NULL,
	CREATED_AT TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP with time zone,
	DELETED INT DEFAULT 0 NOT NULL, 
	DELETED_AT TIMESTAMP with time zone
);